### ISSUE TITLE
Error 400 being returned from MyWaterToronto API

### ISSUE THREAD

**Issue by davecpearce** [davecpearce/hacs_mywatertoronto#129]
Home Assistant is reporting a resultCode 400 - Bad Request error when retrieving hourly data.  The integration requests hourly data for the current day.  It appears that MyWaterToronto service has changed and will not allow you request hourly data  closer than 3 days ago.  The intervals being requested needs to be changed in the integration.

**Comment by davecpearce** [comment]
Given that the water meters only refresh every day or 2, an hourly sensor in HA is meaningless.  Given that you can create template sensors and rely on long term statistics and history cards in HA, I'm going to update the integration to only pull in the total water usage life-to-date and remove all the interval sensors.  This will be a breaking change.

**Comment by jprasm** [comment]
You beat me to it, Dave. Thanks for taking care of this.

**Comment by davecpearce** [comment]
Sorry for the delay on this, it turns out that the MyWaterToronto API seems to be returning an error periodically so I added a retry logic and it seems to be working.  Some of the API calls need to be resubmitted 1 or 2 extra times.  I have published  release V1.4.0.  @jprasm , let me know if this works for you as well and we can close this issue.

**Comment by jprasm** [comment]
Hi Dave, I've go the new version installed and the 400 error is gone (for now). 
The payment type I'm forced to use is "in person"....it still doesn't accept mytorontopay as the last payment method for me (I guess it doesn't matter if it works in the end!). I will keep you posted. Thank you again :)

**Comment by davecpearce** [comment]
The API is currently returning error 400 but the City of Toronto website says "MyWaterToronto is currently undergoing maintenance. We hope to have the maintenance completed shortly and apologize for the inconvenience.".  It's unclear when the service will be available again.
https://www.toronto.ca/services-payments/water-environment/how-to-use-less-water/mywatertoronto/
